# Generated by Django 5.2.3 on 2025-07-16 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('job_position', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Finacial_statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assets', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_saving_enough', models.BooleanField(default=False)),
                ('is_overspending', models.BooleanField(default=False)),
                ('investment_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('emergency_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_debt_hurting', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Financial_goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=50)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_list', to='app.finacial_statements')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.TextField()),
                ('why', models.TextField()),
                ('solution', models.TextField()),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.finacial_statements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_reports', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_type', models.CharField(choices=[('bank', 'Bank Loan'), ('credit', 'Credit Card'), ('personal', 'Personal Loan'), ('mortgage', 'Mortgage'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_items', to='app.finacial_statements')),
            ],
        ),
    ]
