# Generated by Django 5.2.3 on 2025-07-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_finacial_statements_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialadvice',
            old_name='problem',
            new_name='advice_text',
        ),
        migrations.RemoveField(
            model_name='financialadvice',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='financialadvice',
            name='why',
        ),
        migrations.AddField(
            model_name='financialadvice',
            name='can_achieve_goal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialadvice',
            name='is_saving_enough',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialadvice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
