# Generated by Django 5.2.3 on 2025-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_problem_financialadvice_advice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialadvice',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
